### ISSUE TITLE
[ERROR]: Found a reference to a plugin ("http://gareus.org/oss/lv2/gmsynth") that is unknown.

### ISSUE THREAD

**Issue by chris-carneiro** [x42/gmsynth.lv2#4]
Hi.

I'm not sure if this is the right place to ask about this error, I'm really new in this community so please don't kill me :)

I tried to import a tutorial session that uses the gmsynth plugin in a fresh install of Ardour6 (again new to me..) and I get the above error.

I did a bit of research and found that this error could be related to some kind of unique URI that is used to identify a LV2 plugin.. (again not sure I'm using the right words)

Anyways, I landed on the homepage of this project (https://x42-plugins.com/x42/x42-gmsynth) which led me to the source..
I skip the details... I noticed that the URI defined in the source (GFS_URN "http://gareus.org/oss/lv2/gmsynth") was different from the homepage...So my (naive) guess was that the reference to the plugin changed(?) and that it would be the reason I get the error ?

I then tried to change the URI in the source, I also had to change the name of some files to be able to make the project.

Here is What I tried so far : 

I defined the URI like so: GFS_URN "https://x42-plugins.com/x42/x42-gmsynth"
I rename the gmsynth.c file to x42-gmsynth.c
I renamed gmsynth.ttl.in to x42-gmsynth.ttl.in
And changed to URL accordingly everywhere I could find it...

Right now you may have understood that the above didn't work at all.. Hence my presence here and this post that looks like a stackoverflow post... My bad :/

Anyhow, do you have any idea what might be wrong and why Ardour can't use the plugin ?

I feel stuck as I tried what I could with the knowledge I have (I'm not a C developer, and this is the first time I install a DAW )
Thanks for reading!

Edit: I forgot to mention that I've defined my LV2_PATH= $HOME/.lv2 and even tried the system-wide approach and placed the plugin in /usr/lib/lv2. So I guess the Ardour finds the plugin ? I'm obviously missing something...

**Comment by x42** [comment]
URIs in LV2 just serve as a unique identifier. They do not have to point to a valid web-page (but most do for convenience).
The unique ID of the general MIDI synth is `http://gareus.org/oss/lv2/gmsynth` and that has not changed, regardless of the web-page redirecting.

Where did you get Ardour from? binaries from http://ardour.org/download.html do bundle the plugin, but most GNU/Linux distributions do not include it.

Try `lv2ls | grep gmsynth`. If all is setup correctly that should print `http://gareus.org/oss/lv2/gmsynth`.

Canonical way to install the plugin (here using a pre-compiled 64bit Linux version):
```
cd /tmp
wget https://x42-plugins.com/x42/linux/x42-gmsynth-v0.5.0-x86_64.tar.gz
tar xvf x42-gmsynth-v0.5.0-x86_64.tar.gz
mkdir -p ~/.lv2
rm -rf ~/.lv2/gmsynth.lv2
mv x42-gmsynth/gmsynth.lv2/ ~/.lv2/
```
Then restart Ardour (lv2 plugins are indexed at application start).

**Comment by chris-carneiro** [comment]
Wow thanks for the very quick reply!

Here is the output
$ lv2ls | grep gmsynth
https://x42-plugins.com/x42/x42-gmsynth -- that's what I modified in the source but that means the plugin is resolved.

I got Ardour from flathub, my distro is popOS, so I used its package manager.. That might be the problem, maybe I should try to install it from the source ( I admit I was lazy on this one)

**Comment by x42** [comment]
OK. that's the wrong URI. the plugin's ID is http://gareus.org/oss/lv2/gmsynth.

In any case, flatpak is your issue.  Flatpak sanboxes the application. This is conceptually at odds with the concept of 3rd party plugins. The plugin(s) also need to be in the same sandbox as the application to be found.

Please contact flatpak maintainers of the Ardour about it. The flatpak build is neither recommended nor endorsed by Ardour devs.

**Comment by chris-carneiro** [comment]
OK I got the right URL now but the issue remains. 

I'll reinstalled Ardour and contact the flatpak maintainers with the reference to this issue (if you don't mind ? ) to see if they can do something about it.

Thanks for the input and your support.

**Comment by chris-carneiro** [comment]
I found a similar issue [here](https://discourse.ardour.org/t/ardour-is-not-detecting-carla-for-me/104441/7) in case anyone has the same error.

As you mentioned, Ardour should only be installed using the binaries found on the official website.
Thanks again for your time!

**Comment by hfiguiere** [comment]
> I got Ardour from flathub, my distro is popOS, so I used its package manager.. That might be the problem, maybe I should try to install it from the source ( I admit I was lazy on this one)

Since you use the flatpak for Ardour, you might want to instead install `org.freedesktop.LinuxAudio.Plugins.gmsynth` which is the flatpaked version of gmsynth.

**Comment by hfiguiere** [comment]
In which I discover that setting `LV2_PATH` (in the sandbox) does prevent Ardour from looking into `~/.lv2` I will fix this and it should allow plugins installed in `.lv2` to (possibly) work. This plugin would in that case.
